# file: etherpad-servers.yml
- hosts: etherpad-servers
  gather_facts: True
  roles:
    - role: debops.etherpad
      etherpad_version: 'master'
      etherpad_trust_proxy: True
      etherpad_dependencies: True
      tags: 'etherpad_setup'
      
