# file: owncloud-servers.yml
- hosts: owncloud-servers
  gather_facts: True

  roles:
    - role: mount_drive
      mount_dir: "{{ owncloud_data_path }}"
      drive_label: "{{ owncloud_drive_label }}"
      drive_fstype: "{{ owncloud_drive_fstype }}"
      when: owncloud_mount_drive
      tags: mount_that_drive

    - role: debops.owncloud
      owncloud_autosetup: False
      owncloud_dependencies: True 
      # Max upload size set in nginx and php5, with amount as M or G
      owncloud_upload_size: '2G'
      # Output buffering set in php5, with amount set in megabytes
      owncloud_php5_output_buffering: '128'
      owncloud_domain: [ '{{ ansible_fqdn }}' ]

