---
# List of default repositories for Raspbian GNU/Linux

apt_default_sources:
  - comment:  'Raspbian Main Repository'
    mirrors:  [ 'http://mirrordirector.raspbian.org/raspbian/' ]
    releases: [ '{{ apt_sources_release }}' ]
    sections: [ 'main', 'contrib', 'non-free', 'rpi' ]
