---

# List of default repositories for Ubuntu Linux distribution
apt_default_sources:
  - comment:  'Ubuntu Security Repository'
    mirrors:  [ 'http://security.ubuntu.com/ubuntu' ]
    releases: [ '{{ apt_sources_release_security }}' ]
    sections: [ 'main', 'restricted', 'universe', 'multiverse' ]

  - comment:  'Ubuntu Package Repositories'
    releases: '{{ apt_sources_release_list }}'
    sections: [ 'main', 'restricted', 'universe', 'multiverse' ]

  #- comment:  'Ubuntu Partner Repository'
  #  mirrors:  [ 'http://archive.canonical.com/ubuntu' ]
  #  releases: [ '{{ apt_sources_release }}' ]
  #  sections: [ 'partner' ]

  #- comment:  'Ubuntu Extras Repository'
  #  mirrors:  [ 'http://extras.ubuntu.com/ubuntu' ]
  #  releases: [ '{{ apt_sources_release }}' ]
  #  sections: [ 'main' ]

