---

- name: Manage SKS Keyserver
  hosts: 'debops_sks'
  sudo: True

  roles:
    - { role: debops.sks, tags: sks }


- name: Manage iPXE configuration files
  hosts: 'debops_ipxe'
  sudo: True

  roles:
    - { role: debops.ipxe, tags: ipxe }


- name: Manage BoxBackup service
  hosts: 'debops_boxbackup'
  sudo: True

  roles:
    - { role: debops.boxbackup, tags: boxbackup }


- name: Manage rsnapshot service
  hosts: 'debops_rsnapshot:debops_rsnapshot_rsync'
  sudo: True

  roles:
    - { role: debops.rsnapshot, tags: rsnapshot }


- name: Manage Mailman service
  hosts: 'debops_mailman'
  sudo: True

  roles:
    - { role: debops.mailman, tags: mailman }


- name: Manage DokuWiki
  hosts: 'debops_dokuwiki'
  sudo: True

  roles:
    - { role: debops.dokuwiki, tags: dokuwiki }


- name: Manage Etherpad service
  hosts: 'debops_etherpad'
  sudo: True

  roles:
    - { role: debops.etherpad, tags: etherpad }


- name: Manage Preseed server
  hosts: 'debops_preseed'
  sudo: True

  roles:
    - { role: debops.preseed, tags: preseed }


- name: Manage ownCloud service
  hosts: 'debops_owncloud'
  sudo: True

  roles:
    - { role: debops.owncloud, tags: owncloud }


- name: Manage phpIPAM service
  hosts: 'debops_phpipam'
  sudo: True

  roles:
    - { role: debops.phpipam, tags: phpipam }


- name: Manage RStudio Server
  hosts: 'debops_rstudio_server'
  sudo: True

  roles:
    - { role: debops.rstudio_server, tags: rstudio_server }


- name: Manage GitLab service
  hosts: 'debops_gitlab'
  sudo: True

  roles:
    - { role: debops.gitlab, tags: gitlab }

- name: Manage GitLab CI service
  hosts: 'debops_gitlab_ci'
  sudo: True

  roles:
    - { role: debops.gitlab_ci, tags: gitlab_ci }

- name: Manage GitLab CI Runner service
  hosts: 'debops_gitlab_ci_runner'
  sudo: True

  roles:
    - { role: debops.gitlab_ci_runner, tags: gitlab_ci_runner }


- name: Install DebOps recursively
  hosts: 'debops_recursively'
  sudo: True

  roles:
    - { role: debops.debops, tags: debops }

