---

- include: root.yml

- name: Common configuration for all hosts
  hosts: 'all:!localhost'
  gather_facts: True
  sudo: True

  roles:
    - { role: debops.apt_preferences,      tags: apt_preferences }
    - { role: debops.etc_services,         tags: etc_services }
    - { role: debops.pki,                  tags: pki }
    - { role: debops.auth,                 tags: auth }
    - { role: debops.apt,                  tags: apt }
    - { role: debops.ferm,                 tags: ferm }
    - { role: debops.tcpwrappers,          tags: tcpwrappers }
    - { role: debops.ntp,                  tags: ntp }
    - { role: debops.ifupdown,             tags: ifupdown }
    - { role: debops.console,              tags: console }
    - { role: debops.postfix,              tags: postfix }
    - { role: debops.rsyslog,              tags: rsyslog }
    - { role: debops.users,                tags: users }
    - { role: debops.sshkeys,              tags: sshkeys }
    - { role: debops.sshd,                 tags: sshd }
    - { role: debops.directories,          tags: directories }

