---

- name: Manage NodeJS environment
  hosts: 'debops_nodejs'
  sudo: True

  roles:
    - { role: debops.nodejs, tags: nodejs }


- name: Manage Ruby environment
  hosts: 'debops_ruby'
  sudo: True

  roles:
    - { role: debops.ruby, tags: ruby }


- name: Manage Go environment
  hosts: 'debops_golang'
  sudo: True

  roles:
    - { role: debops.golang, tags: golang }


- name: Manage Java environment
  hosts: 'debops_java'
  sudo: True

  roles:
    - { role: debops.java, tags: java }


- name: Manage PHP5 environment
  hosts: 'debops_php5'
  sudo: True

  roles:
    - { role: debops.php5, tags: php5 }

