---

- name: Configure internal networks
  hosts: 'debops_subnetwork'
  sudo: True

  roles:
    - { role: debops.subnetwork, tags: subnetwork }


- name: Configure Router Advertisement Daemon
  hosts: 'debops_radvd'
  sudo: True

  roles:
    - { role: debops.radvd, tags: radvd }


- name: Manage ISC DHCP server
  hosts: 'debops_dhcpd'
  sudo: True

  roles:
    - { role: debops.dhcpd, tags: dhcpd }


- name: Configure dnsmasq
  hosts: debops_dnsmasq
  sudo: True

  roles:
    - { role: debops.dnsmasq, tags: dnsmasq }


- name: Configure tinc VPN
  hosts: debops_tinc
  sudo: True

  roles:
    - { role: debops.tinc, tags: tinc }


- name: Configure stunnel
  hosts: debops_stunnel
  sudo: True

  roles:
    - { role: debops.stunnel, tags: stunnel }

