---

- name: Manage nginx server
  hosts: 'debops_nginx'
  sudo: True

  roles:
    - { role: debops.nginx, tags: nginx }


- name: Manage SNMP service
  hosts: 'debops_snmpd'
  sudo: True

  roles:
    - { role: debops.snmpd, tags: snmpd }


- name: Manage Monit service
  hosts: 'debops_monit'
  sudo: True

  roles:
    - { role: debops.monit, tags: monit }


- name: Manage Dovecot service
  hosts: 'debops_dovecot'
  sudo: True

  roles:
    - { role: debops.dovecot, tags: dovecot }


- name: Manage TFTP service
  hosts: 'debops_tftpd'
  sudo: True

  roles:
    - { role: debops.tftpd, tags: tftpd }


- name: Manage Samba service
  hosts: 'debops_samba'
  sudo: True

  roles:
    - { role: debops.samba, tags: samba }


- name: Manage iSCSI Target service
  hosts: 'debops_tgt'
  sudo: True

  roles:
    - { role: debops.tgt, tags: tgt }


- name: Manage MariaDB server
  hosts: 'debops_mariadb_server'
  sudo: True

  roles:
    - { role: debops.mariadb_server, tags: mariadb_server }


- name: Manage MariaDB client
  hosts: 'debops_mariadb'
  sudo: True

  roles:
    - { role: debops.mariadb, tags: mariadb }


- name: Manage MySQL server
  hosts: 'debops_mysql'
  sudo: True

  roles:
    - { role: debops.mysql, tags: mysql }

    - role: debops.phpmyadmin
      when: mysql_phpmyadmin is defined and mysql_phpmyadmin
      tags: [ 'mysql', 'phpmyadmin' ]


- name: Manage PostgreSQL server
  hosts: 'debops_postgresql'
  sudo: True

  roles:
    - { role: debops.postgresql, tags: postgresql }


- name: Manage Elasticsearch server
  hosts: 'debops_elasticsearch_master:debops_elasticsearch_workhorse:debops_elasticsearch_coordinator:debops_elasticsearch_loadbalancer'
  sudo: True

  roles:
    - { role: debops.elasticsearch, tags: elasticsearch }


- name: Manage memcached server
  hosts: 'debops_memcached'
  sudo: True

  roles:
    - { role: debops.memcached, tags: memcached }


- name: Manage Redis server
  hosts: 'debops_redis'
  sudo: True

  roles:
    - { role: debops.redis, tags: redis }


- name: Manage Redis sentinel server
  hosts: 'debops_redis_sentinel'
  sudo: True

  roles:
    - { role: debops.redis, tags: redis }


- name: Manage reprepro repositories
  hosts: 'debops_reprepro'
  sudo: True

  roles:
    - { role: debops.reprepro, tags: reprepro }


- name: Manage SMS gateway
  hosts: 'debops_smstools'
  sudo: True

  roles:
    - { role: debops.smstools, tags: smstools }


- name: Manage Salt master service
  hosts: 'debops_salt'
  sudo: True

  roles:
    - { role: debops.salt, tags: salt }


- name: Manage fail2ban service
  hosts: 'debops_fail2ban'
  sudo: True

  roles:
    - { role: debops.fail2ban, tags: fail2ban }

