---

- name: Manage KVM hosts
  hosts: 'debops_kvm'
  sudo: True

  roles:
    - { role: debops.kvm, tags: kvm }


- name: Manage LXC hosts
  hosts: 'debops_lxc'
  sudo: True

  roles:
    - { role: debops.lxc, tags: lxc }


- name: Manage OpenVZ Hardware Nodes
  hosts: 'debops_openvz'
  sudo: True

  roles:
    - { role: debops.openvz, tags: openvz }

